## Kaggle Competition

In [43]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.decomposition import PCA

In [44]:
train = pd.read_csv('train_digits.csv')

In [45]:
test = pd.read_csv('test_digits.csv')

In [46]:
train.shape

(42000, 785)

In [47]:
test.shape

(28000, 784)

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
train.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [50]:
test.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [51]:
y = train.iloc[:,0]

In [52]:
y.head()

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

In [53]:
X = train.iloc[:,1:]

In [54]:
X.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.20, random_state=12)

***Use randomforest and knn to predict digits data***

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
clf = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=222)

In [19]:
clf.fit(X_train,y_train)

RandomForestClassifier(max_depth=2, random_state=222)

In [20]:
pred=clf.predict(X_test)

In [21]:
np.sum(pred==y_test)/len(y_test)

0.6482142857142857

***65% accuracy, not very good***

In [27]:
from sklearn.svm import SVC

In [28]:
svc = SVC()

In [29]:
svc.fit(X_train,y_train)

SVC()

In [30]:
pred = svc.predict(X_test)

In [37]:
np.sum(pred==y_test)/len(y_test)

0.09047619047619047

***This is not as good as a model***

In [56]:
from sklearn.neighbors import KNeighborsClassifier

In [57]:
knn = KNeighborsClassifier(n_neighbors=5)

In [58]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [59]:
pred=knn.predict(X_test)

In [60]:
np.sum(pred==y_test)/len(y_test)

0.9654761904761905

***Knn is very accurate and previous attempts at scaling made our model worse, lets improve just a little more***

In [24]:
from sklearn.model_selection import GridSearchCV

In [26]:
param_grid = {
    'n_neighbors': [1],
    'weights': ['uniform','distance'],
    'algorithm': ['auto','ball_tree','kd_tree','brute']
}
knn = KNeighborsClassifier()

grid_search = GridSearchCV(
    knn, param_grid, cv=10, scoring='accuracy')#C is how many folds we want
grid_search.fit(X_train, y_train)

GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [1],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [29]:
knn = grid_search.best_estimator_

In [31]:
knn

KNeighborsClassifier(n_neighbors=1)

In [32]:
grid_search.best_score_

0.9661309523809523

In [34]:
grid_search.best_params_

{'algorithm': 'auto', 'n_neighbors': 1, 'weights': 'uniform'}

In [27]:
knn = grid_search.best_estimator_

In [35]:
knn = KNeighborsClassifier(algorithm= 'auto', n_neighbors= 1, weights='uniform')

In [36]:
knn

KNeighborsClassifier(n_neighbors=1)

In [154]:
X = train.iloc[:,1:]
y = train.iloc[:,0]
knn.fit(X,y)

KNeighborsClassifier(n_neighbors=1)

In [155]:
pred = knn.predict(test)

In [156]:
pred = np.array(pred)

In [157]:
pred

array([2, 0, 9, ..., 3, 9, 2])

In [158]:
col = list(range(1, 28001))
col = np.array(col)

In [159]:
df = pd.DataFrame({'ImageId':col, 'Label':pred})

In [160]:
col.shape

(28000,)

In [161]:
pred.shape

(28000,)

In [162]:
df.to_csv('Digits_Predicitions.csv', index=False)

***Only 97% accuracy, lets try to do some PCA and do better***

In [39]:
pca = PCA(n_components=.80)

In [40]:
pca.fit(X)

PCA(n_components=0.8)

In [41]:
pca.explained_variance_ratio_

array([0.09748938, 0.07160266, 0.06145903, 0.05379302, 0.04894262,
       0.04303214, 0.03277051, 0.02892103, 0.02766902, 0.02348871,
       0.02099325, 0.02059001, 0.01702553, 0.01692787, 0.01581126,
       0.0148324 , 0.01319688, 0.01282727, 0.01187976, 0.01152755,
       0.01072191, 0.01015199, 0.00964902, 0.00912846, 0.00887641,
       0.00838766, 0.00811856, 0.00777406, 0.00740635, 0.00686661,
       0.00657982, 0.00638799, 0.00599367, 0.00588913, 0.00564335,
       0.00540967, 0.00509222, 0.00487505, 0.00475569, 0.00466545,
       0.00452952, 0.00444989, 0.00418255])

In [42]:
Transformed=pca.transform(X)

In [43]:
Transformed.shape

(42000, 43)

In [44]:
X2=pca.inverse_transform(Transformed)

In [45]:
X2

array([[ 6.35165477e-15, -7.29644092e-14,  7.52773990e-14, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-9.28390545e-16, -2.02312095e-13, -2.91378731e-13, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 4.28076507e-16,  2.36671951e-14, -1.95002739e-14, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 1.29928943e-16, -2.59482512e-13, -7.79294189e-14, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.74460013e-15,  2.92038816e-14,  5.91109466e-14, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.17294224e-16, -4.47900826e-14,  1.08918149e-13, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [46]:
X2.shape

(42000, 784)

In [47]:
X.shape

(42000, 784)

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X2, y, test_size=.10, random_state=12)

In [49]:
knn = KNeighborsClassifier(n_neighbors=1)

In [50]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [51]:
pred=knn.predict(X_test)

In [52]:
np.sum(pred==y_test)/len(y_test)

0.9759523809523809

In [53]:
pred = knn.predict(test)

In [54]:
pred

array([2, 0, 9, ..., 3, 9, 2])

In [55]:
col = list(range(1, 28001))
col = np.array(col)

In [56]:
df = pd.DataFrame({'ImageId':col, 'Label':pred})

In [57]:
df.to_csv('Digits_Predicitions.csv', index=False)

In [58]:
X2

array([[ 6.35165477e-15, -7.29644092e-14,  7.52773990e-14, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-9.28390545e-16, -2.02312095e-13, -2.91378731e-13, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 4.28076507e-16,  2.36671951e-14, -1.95002739e-14, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 1.29928943e-16, -2.59482512e-13, -7.79294189e-14, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.74460013e-15,  2.92038816e-14,  5.91109466e-14, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.17294224e-16, -4.47900826e-14,  1.08918149e-13, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

### Artifical neural networks

In [120]:
X,y = train.iloc[:,1:], train.iloc[:,0]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.20, random_state=12)

In [121]:
y_test.unique()

array([2, 5, 4, 7, 6, 1, 3, 9, 8, 0])

In [122]:
import tensorflow as tf

In [123]:
ann = tf.keras.models.Sequential()

In [124]:
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

In [125]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [126]:
ann.add(tf.keras.layers.Dense(units=1, activation='softmax'))

In [127]:
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ["accuracy"])

In [128]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 20)

Epoch 1/20
1050/1050 [==============================] - 1s 982us/step - loss: 0.0000e+00 - accuracy: 0.1115
Epoch 2/20
1050/1050 [==============================] - 1s 927us/step - loss: 0.0000e+00 - accuracy: 0.1115
Epoch 3/20
1050/1050 [==============================] - 1s 923us/step - loss: 0.0000e+00 - accuracy: 0.1115
Epoch 4/20
1050/1050 [==============================] - 1s 930us/step - loss: 0.0000e+00 - accuracy: 0.1115
Epoch 5/20
1050/1050 [==============================] - 1s 926us/step - loss: 0.0000e+00 - accuracy: 0.1115
Epoch 6/20
1050/1050 [==============================] - 1s 924us/step - loss: 0.0000e+00 - accuracy: 0.1115
Epoch 7/20
1050/1050 [==============================] - 1s 928us/step - loss: 0.0000e+00 - accuracy: 0.1115
Epoch 8/20
1050/1050 [==============================] - 1s 926us/step - loss: 0.0000e+00 - accuracy: 0.1115
Epoch 9/20
1050/1050 [==============================] - 1s 947us/step - loss: 0.0000e+00 - accuracy: 0.1115
Epoch 10/20
1050/1050 [=====

In [114]:
pred = ann.predict(X_test)

263/263 [==============================] - 0s 796us/step


In [115]:
pred.size

8400

In [116]:
X_test.shape

(8400, 784)

In [117]:
pred = pd.DataFrame(pred)

In [119]:
pred.tail()

0
8395  1.0
8396  1.0
8397  1.0
8398  1.0
8399  1.0

### Knn was the best model I could find